final check

diff --git a/cloudbuild_test_gcloud.yaml b/cloudbuild_test_gcloud.yaml
--- a/cloudbuild_test_gcloud.yaml
+++ b/cloudbuild_test_gcloud.yaml
@@ -87,19 +87,6 @@ steps:
   allowFailure: true
   waitFor: ['create gke cluster']
 
-- id: "Test kubectl with more commands"
-  name: "gcr.io/cloud-builders/kubectl"
-  env:
-    - "CLOUDSDK_COMPUTE_ZONE=${_REGION}"
-    - "CLOUDSDK_CONTAINER_CLUSTER=ml-373a855--7e5eca7e-cluster"
-  entrypoint: 'sh'
-  args:
-  - '-c'
-  - |
-    set -e
-    kubectl get nodes
-    kubectl get secrets
-
 - id: 'create ray cluster'
   name: "hashicorp/terraform:latest"
   allowFailure: true
@@ -327,58 +314,58 @@ steps:
   - '-c'
   - |
     set -e
+    echo "This is mocked step that should be implemented later."
+    # # Validate Ray: Make sure pods are running
+    # kubectl wait --for=condition=Ready pods -n rag-$SHORT_SHA-$_BUILD_ID -l 'component!=continuous-image-puller' --timeout=1200s
+    # kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8262:8265 &
+    # # Wait port-forwarding to take its place
+    # sleep 5s
 
-    # Validate Ray: Make sure pods are running
-    kubectl wait --for=condition=Ready pods -n rag-$SHORT_SHA-$_BUILD_ID -l 'component!=continuous-image-puller' --timeout=1200s
-    kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8262:8265 &
-    # Wait port-forwarding to take its place
-    sleep 5s
+    # # Install Python requirements
+    # apt update
+    # apt install python3-venv --assume-yes
+    # apt install python3-pip --assume-yes
+    # pip install -U "ray[data,train,tune,serve]"
+    # pip install pyyaml requests packaging
 
-    # Install Python requirements
-    apt update
-    apt install python3-venv --assume-yes
-    apt install python3-pip --assume-yes
-    pip install -U "ray[data,train,tune,serve]"
-    pip install pyyaml requests packaging
+    # # Validate Ray: Check dashboard
+    # ray job submit --working-dir ./tests \
+    # --address=http://127.0.0.1:8262 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
+    # echo "pass" > /workspace/rag_ray_dashboard_result.txt
 
-    # Validate Ray: Check dashboard
-    ray job submit --working-dir ./tests \
-    --address=http://127.0.0.1:8262 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
-    echo "pass" > /workspace/rag_ray_dashboard_result.txt
+    # # Validate JupyterHub: Get hub url
+    # kubectl get services -n rag-$SHORT_SHA-$_BUILD_ID
+    # kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
+    # # Wait port-forwarding to take its place
+    # sleep 5s
 
-    # Validate JupyterHub: Get hub url
-    kubectl get services -n rag-$SHORT_SHA-$_BUILD_ID
-    kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
-    # Wait port-forwarding to take its place
-    sleep 5s
+    # # Validate JupyterHub: Test Hub
+    # cd /workspace/common/modules/jupyter/tests
+    # python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
+    # echo "pass" > /workspace/rag_jupyterhub_test_result.txt
 
-    # Validate JupyterHub: Test Hub
-    cd /workspace/common/modules/jupyter/tests
-    python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
-    echo "pass" > /workspace/rag_jupyterhub_test_result.txt
+    # # Validate RAG: Test rag frontend
+    # kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/rag-frontend 8081:8080 &
+    # # Wait port-forwarding to take its place
+    # sleep 5s
 
-    # Validate RAG: Test rag frontend
-    kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/rag-frontend 8081:8080 &
-    # Wait port-forwarding to take its place
-    sleep 5s
+    # cd /workspace/rag/tests
+    # python3 test_frontend.py "127.0.0.1:8081"
+    # echo "pass" > /workspace/rag_frontend_result.txt
 
-    cd /workspace/rag/tests
-    python3 test_frontend.py "127.0.0.1:8081"
-    echo "pass" > /workspace/rag_frontend_result.txt
+    # cd /workspace/
+    # sed -i "s/<username>/$$KAGGLE_USERNAME/g" ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
+    # sed -i "s/<token>/$$KAGGLE_KEY/g" ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
+    # gsutil cp ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb gs://gke-aieco-rag-$SHORT_SHA-$_BUILD_ID/
+    # kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID $(kubectl get pod -l app=jupyterhub,component=hub -n rag-$SHORT_SHA-$_BUILD_ID -o jsonpath="{.items[0].metadata.name}") -- jupyterhub token admin --log-level=CRITICAL | xargs python3 ./rag/notebook_starter.py
+    # # Wait for jupyterhub to trigger notebook pod startup
+    # sleep 5s
+    # kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID --timeout=500s
+    # kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- jupyter nbconvert --to script /data/rag-kaggle-ray-sql-interactive.ipynb
+    # kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- ipython /data/rag-kaggle-ray-sql-interactive.py
 
-    cd /workspace/
-    sed -i "s/<username>/$$KAGGLE_USERNAME/g" ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
-    sed -i "s/<token>/$$KAGGLE_KEY/g" ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
-    gsutil cp ./rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb gs://gke-aieco-rag-$SHORT_SHA-$_BUILD_ID/
-    kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID $(kubectl get pod -l app=jupyterhub,component=hub -n rag-$SHORT_SHA-$_BUILD_ID -o jsonpath="{.items[0].metadata.name}") -- jupyterhub token admin --log-level=CRITICAL | xargs python3 ./rag/notebook_starter.py
-    # Wait for jupyterhub to trigger notebook pod startup
-    sleep 5s
-    kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID --timeout=500s
-    kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- jupyter nbconvert --to script /data/rag-kaggle-ray-sql-interactive.ipynb
-    kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- ipython /data/rag-kaggle-ray-sql-interactive.py
-
-    python3 ./rag/tests/test_rag.py "http://127.0.0.1:8081/prompt"
-    echo "pass" > /workspace/rag_prompt_result.txt
+    # python3 ./rag/tests/test_rag.py "http://127.0.0.1:8081/prompt"
+    # echo "pass" > /workspace/rag_prompt_result.txt
 
 - id: 'cleanup rag'
   name: "hashicorp/terraform:latest"
@@ -411,182 +398,89 @@ steps:
     -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
     -auto-approve -no-color
 
-# - id: 'test rag'
-#   name: 'gcr.io/$PROJECT_ID/terraform'
-#   entrypoint: 'sh'
-#   secretEnv: ['KAGGLE_USERNAME', 'KAGGLE_KEY']
-#   args:
-#   - '-c'
-#   - |
-#     set -e
+- id: 'cleanup gke cluster'
+  name: "hashicorp/terraform:latest"
+  dir: "/workspace/common/infrastructure/"
+  allowFailure: true
+  waitFor: ['cleanup ray cluster', 'cleanup jupyterhub', 'cleanup rag']
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    set -e
 
-#     # Get kube config
-#     gcloud container clusters get-credentials \
-#     ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-#     --location $_REGION \
-#     --project $PROJECT_ID
+    echo "cleanup gke cluster step!"
+    terraform destroy \
+    -var-file=tfvars_tests/standard-gke-public.platform.tfvars \
+    -var=project_id=$PROJECT_ID \
+    -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
+    -var=subnetwork_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
+    -var=subnetwork_region=$_REGION \
+    -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
+    -var=autopilot_cluster=$_AUTOPILOT_CLUSTER \
+    -var=cluster_location=$_REGION \
+    -var='cpu_pools=[{initial_node_count=2,name="cpu-pool",machine_type="n1-standard-16",autoscaling=true,min_count=1,max_count=3,disk_size_gb=100,disk_type="pd-standard",}]' \
+    -var='gpu_pools=[{initial_node_count=2,name="gpu-pool",machine_type="g2-standard-24",autoscaling=true,min_count=1,max_count=3,disk_size_gb=100,disk_type="pd-balanced",accelerator_count=2,accelerator_type="nvidia-l4",gpu_driver_version="DEFAULT",}]' \
+    -auto-approve -no-color
 
-#     cd /workspace/modules/jupyter/tests
-#     python3 change_jupyter_config.py $_AUTOPILOT_CLUSTER
+- id: 'check result'
+  # name: 'gcr.io/$PROJECT_ID/terraform'
+  name: "hashicorp/terraform:latest"
+  entrypoint: 'sh'
+  args:
+  - '-c'
+  - |
+    if [[ $(cat /workspace/gke_cluster_result.txt) != "pass" ]]; then
+      echo "gke cluster creation failed"
+      exit 1
+    fi
 
-#     cd /workspace/applications/rag/
-#     terraform apply \
-#     -var-file=workloads.tfvars \
-#     -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-#     -var=create_cluster=false \
-#     -var=jupyter_add_auth=false \
-#     -var=frontend_add_auth=false \
-#     -var=project_id=$PROJECT_ID \
-#     -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-#     -var=cluster_location=$_REGION \
-#     -var=kubernetes_namespace=rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=gcs_bucket=gke-aieco-rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=ray_service_account=ray-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=rag_service_account=rag-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=jupyter_service_account=jupyter-sa-4-rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
-#     -auto-approve -no-color
-#     echo "pass" > /workspace/rag_tf_result.txt
+    if [[ $(cat /workspace/user_result.txt) != "pass" ]]; then
+      echo "ray creation tf failed"
+      exit 1
+    fi
 
-#     # Validate Ray: Make sure pods are running
-#     kubectl wait --for=condition=Ready pods -n rag-$SHORT_SHA-$_BUILD_ID -l 'component!=continuous-image-puller' --timeout=1200s
-#     kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/ray-cluster-kuberay-head-svc 8262:8265 &
-#     # Wait port-forwarding to take its place
-#     sleep 5s
+    if [[ $(cat /workspace/ray_result.txt) != "pass" ]]; then
+      echo "ray test failed"
+      exit 1
+    fi
 
-#     # Validate Ray: Check dashboard
-#     ray job submit --working-dir ./tests \
-#     --address=http://127.0.0.1:8262 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
-#     echo "pass" > /workspace/rag_ray_dashboard_result.txt
+    if [[ $(cat /workspace/jupyterhub_tf_result.txt) != "pass" ]]; then
+      echo "jupyterhub creation tf failed"
+      exit 1
+    fi
 
-#     # Validate JupyterHub: Get hub url
-#     kubectl get services -n rag-$SHORT_SHA-$_BUILD_ID
-#     kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/proxy-public 9443:80 &
-#     # Wait port-forwarding to take its place
-#     sleep 5s
+    if [[ $(cat /workspace/jupyterhub_test_result.txt) != "pass" ]]; then
+      echo "jupyterhub test failed"
+      exit 1
+    fi
 
-#     # Validate JupyterHub: Test Hub
-#     cd /workspace/modules/jupyter/tests
-#     python3 test_hub.py "127.0.0.1:9443" $_AUTOPILOT_CLUSTER
-#     echo "pass" > /workspace/rag_jupyterhub_test_result.txt
+    if [[ $(cat /workspace/jupyterhub_test_result.txt) != "pass" ]]; then
+      echo "jupyterhub test failed"
+      exit 1
+    fi
 
-#     # Validate RAG: Test rag frontend
-#     kubectl port-forward -n rag-$SHORT_SHA-$_BUILD_ID service/rag-frontend 8081:8080 &
-#     # Wait port-forwarding to take its place
-#     sleep 5s
+    if [[ $(cat /workspace/rag_tf_result.txt) != "pass" ]]; then
+      echo "rag tf failed"
+      exit 1
+    fi
 
-#     cd /workspace/applications/rag/tests
-#     python3 test_frontend.py "127.0.0.1:8081"
-#     echo "pass" > /workspace/rag_frontend_result.txt
+    # if [[ $(cat /workspace/rag_jupyterhub_test_result.txt) != "pass" ]]; then
+    #   echo "rag jupyterhub test failed"
+    #   exit 1
+    # fi
 
-#     cd /workspace/
-#     sed -i "s/<username>/$$KAGGLE_USERNAME/g" ./applications/rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
-#     sed -i "s/<token>/$$KAGGLE_KEY/g" ./applications/rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb
-#     gsutil cp ./applications/rag/example_notebooks/rag-kaggle-ray-sql-interactive.ipynb gs://gke-aieco-rag-$SHORT_SHA-$_BUILD_ID/
-#     kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID $(kubectl get pod -l app=jupyterhub,component=hub -n rag-$SHORT_SHA-$_BUILD_ID -o jsonpath="{.items[0].metadata.name}") -- jupyterhub token admin --log-level=CRITICAL | xargs python3 ./applications/rag/notebook_starter.py
-#     # Wait for jupyterhub to trigger notebook pod startup
-#     sleep 5s
-#     kubectl wait --for=condition=Ready pod/jupyter-admin -n rag-$SHORT_SHA-$_BUILD_ID --timeout=500s
-#     kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- jupyter nbconvert --to script /data/rag-kaggle-ray-sql-interactive.ipynb
-#     kubectl exec -it -n rag-$SHORT_SHA-$_BUILD_ID jupyter-admin -c notebook -- ipython /data/rag-kaggle-ray-sql-interactive.py
+    # if [[ $(cat /workspace/rag_frontend_result.txt) != "pass" ]]; then
+    #   echo "rag frontend test failed"
+    #   exit 1
+    # fi
 
-#     python3 ./applications/rag/tests/test_rag.py "http://127.0.0.1:8081/prompt"
-#     echo "pass" > /workspace/rag_prompt_result.txt
+    # if [[ $(cat /workspace/ray_result.txt) != "pass" ]]; then
+    #   echo "rag prompt test failed"
+    #   exit 1
+    # fi
 
-#   allowFailure: true
-#   waitFor: ['create gke cluster']
-
-# - id: 'cleanup rag'
-#   name: 'gcr.io/$PROJECT_ID/terraform'
-#   entrypoint: 'bash'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     cd /workspace/applications/rag/
-#     terraform destroy \
-#     -var-file=workloads.tfvars \
-#     -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-#     -var=create_cluster=false \
-#     -var=jupyter_add_auth=false \
-#     -var=frontend_add_auth=false \
-#     -var=project_id=$PROJECT_ID \
-#     -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-#     -var=cluster_location=$_REGION \
-#     -var=kubernetes_namespace=rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=gcs_bucket=gke-aieco-rag-$SHORT_SHA-$_BUILD_ID \
-#     -var=ray_service_account=ray-sa-$SHORT_SHA-$_BUILD_ID \
-#     -var=rag_service_account=rag-sa-$SHORT_SHA-$_BUILD_ID \
-#     -var=jupyter_service_account=jupyter-sa-$SHORT_SHA-$_BUILD_ID \
-#     -var=cloudsql_instance=pgvector-instance-$SHORT_SHA-$_BUILD_ID \
-#     -auto-approve -no-color
-#   allowFailure: true
-#   waitFor: ['test rag']
-
-# - id: 'cleanup gke cluster'
-#   # name: 'gcr.io/$PROJECT_ID/terraform'
-#   name: "hashicorp/terraform:latest"
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     set -e
-
-#     echo "cleanup gke cluster step!"
-#     # terraform destroy -var-file=tfvars_tests/standard-gke-public.platform.tfvars -var=project_id=$PROJECT_ID \
-#     # -var=cluster_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-cluster \
-#     # -var=network_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-#     # -var=subnetwork_name=ml-$SHORT_SHA-$_PR_NUMBER-$_BUILD_ID-$_AUTOPILOT_CLUSTER  \
-#     # -var=autopilot_cluster=$_AUTOPILOT_CLUSTER \
-#     # -var=cluster_location=$_REGION -auto-approve -no-color
-
-#   dir: "common/infrastructure/"
-#   allowFailure: true
-#   waitFor: ['cleanup rag']
-
-# - id: 'check result'
-#   # name: 'gcr.io/$PROJECT_ID/terraform'
-#   name: "hashicorp/terraform:latest"
-#   entrypoint: 'sh'
-#   args:
-#   - '-c'
-#   - |
-#     if [[ $(cat /workspace/gke_cluster_result.txt) != "pass" ]]; then
-#       echo "gke cluster creation failed"
-#       exit 1
-#     fi
-
-#     if [[ $(cat /workspace/rag_tf_result.txt) != "pass" ]]; then
-#       echo "rag tf failed"
-#       exit 1
-#     fi
-
-#     if [[ $(cat /workspace/rag_jupyterhub_test_result.txt) != "pass" ]]; then
-#       echo "rag jupyterhub test failed"
-#       exit 1
-#     fi
-
-#     if [[ $(cat /workspace/rag_frontend_result.txt) != "pass" ]]; then
-#       echo "rag frontend test failed"
-#       exit 1
-#     fi
-
-#     if [[ $(cat /workspace/rag_prompt_result.txt) != "pass" ]]; then
-#       echo "rag prompt test failed"
-#       exit 1
-#     fi
-
-#     if grep -q "Validation failed" /workspace/shipshape_on_cluster.txt; then
-#       echo "Shipshape on cluster scan validation failed, please check the log. knowledge share slides: go/shipshape-ai-on-gke-slide"
-#       exit 1
-#     fi
-
-#     if grep -q "Validation failed" /workspace/shipshape_on_helm.txt; then
-#       echo "Shipshape on helm scan validation failed, please check the log. knowledge share slides: go/shipshape-ai-on-gke-slide"
-#       exit 1
-#     fi
-  # waitFor: ['cleanup gke cluster']
+  waitFor: ['cleanup gke cluster']
 
 substitutions:
   _REGION: us-east4
